### ISSUE TITLE
Accurate 3D model?

### ISSUE THREAD

**Issue by rrattinypcbs** [LattePandaTeam/LattePanda-3D-Models#2]
Hello,

 SAMTEC 2.54mm TSW (TSW-124-05-G-D) does not perfectly mate with LattePandaAlpha 3D model 'LattePanda Alpha 3D Model_181023.stp' 24x2 does not line up. Why is there spacing so have to use 12x2 x2? Where is dimension pin1 to pin1 of 12x2 to each other? Or better where is dxf of all board?

**Comment by rrattinypcbs** [comment]
24x2 does not line up. Why is there spacing so have to use 12x2 x2? Where is dimension pin1 to pin1 of 12x2 to each other? Or better where is dxf of all board?

**Comment by alphaarea** [comment]
I noticed that in the `LattePanda Alpha 3D Model_181023.stp` model, one of the socket headers is incorrectly drawn at 2.94mm pitch. 

LattePanda Alpha is actually all standard 2.54mm, it is recommended to draw the PCB with 2.54mm pitch, based on the first one on the right side (near USB-C and HDMI side).
